language: cpp
dist: trusty
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-8']
          env: COMPILER=g++-8

        - os: osx
          osx_image: xcode10
          compiler: clang
          env: COMPILER=clang++

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="${COMPILER}" ..
    - make -j8


