language: cpp
dist: trusty
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7']
          env: COMPILER=g++-7

        - os: osx
          osx_image: xcode10
          compiler: clang
          env: COMPILER=g++7

script:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew install gcc@7;
      fi
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="${COMPILER}" ..
    - make -j8


